### ISSUE TITLE
Postgresql support

### ISSUE THREAD

**Issue by Acciaiodigitale** [tightenco/lambo#100]
Hi @mattstauffer, I read about Lambo from your excellent Laravel book.

Actually there is support only for mysql. 

Are you thinking of implementing also Postgres as an alternative?

Also could be interesting to add direct support for this [TALL preset](https://github.com/laravel-frontend-presets/tall)

What you think? Can I be of some help?

**Comment by mattstauffer** [comment]
@Acciaiodigitale Hey, glad you found it!

I think adding postgres support is a very interesting idea. I'm open to it if someone has a way to PR it cleanly; if you'd like to do that you're welcome, but the main thing is trying to add it in a way that doesn't make the code or UI more complicated for the majority of users who are using MySQL.

In terms of the presets, we're currently working on building out an idea of presets in Lambo itsself, so there would be a "tall stack" preset you can apply when you use lambo that would trigger that preset you linked.

Thanks! :)

**Comment by Acciaiodigitale** [comment]
I removed the PR because it gives some problem with console output. But I'm working on it
