### ISSUE TITLE
Drop laravel/installer requirement?

### ISSUE THREAD

**Issue by benswinburne** [tightenco/lambo#12]
Could you not use

```
composer create-project laravel/laravel $PROJECTNAME --prefer-dist
```

rather than

```
laravel new $PROJECTNAME
```

allowing you to drop the requirement for a globally installed Laravel installer?

Or, (I don't know if this would work but I don't see why it wouldn't) make `laravel/installer` a dependency of `tightenco/lambo` and run it from the lambo bin dir rather than have that extra global dependency?

**Comment by mattstauffer** [comment]
Hm. I'm curious about the dependency idea. 

The Laravel installer is better and faster than Composer create-project (honestly, I don't even know what is different, but somehow it manages to be better), so I don't want to drop it.

But dependency is an interesting idea.

**Comment by benswinburne** [comment]
I just looked at the laravel installer. It downloads `http://cabinet.laravel.com/latest.zip` and extracts it.

I suppose as such the difference is the source of the zip file, Github (or similar VCS) or Laravel.com. Without looking at Composer's source, whether or not that connects to the API or just CURLs something like `https://github.com/tightenco/lambo/archive/master.zip` I don't know.

**Comment by hulkur** [comment]
> Laravel installer not installed.

I think that as long laravel installer is used it should be required dependency

**Comment by milose** [comment]
Isn't it?

**Comment by hulkur** [comment]
https://github.com/tightenco/lambo/blob/master/composer.json#L13

```
    "require": {
        "php": ">=5.5.9"
    },

```

**Comment by mattstauffer** [comment]
Yah, I think adding it to Lambo's require block would be a good idea.
