### ISSUE TITLE
RE Ternary todo

### ISSUE THREAD

**Issue by benswinburne** [tightenco/lambo#13]
Regarding https://github.com/tightenco/lambo/blob/master/lambo#L114

    prettyPath=$([ "$PROJECTPATH" == "." ] && \
        echo "$PROJECTNAME" || \
        echo "$PROJECTPATH/$PROJECTNAME")

    [[ $PROJECTPATH = "." ]] && \
        prettyPath="$PROJECTNAME" || \
        prettyPath="$PROJECTPATH/$PROJECTNAME"

    case $PROJECTNAME in
     .) prettyPath="$PROJECTNAME" ;;
     *) prettyPath="$PROJECTPATH/$PROJECTNAME" ;;
    esac

Some syntax choices for you. Can PR later if needs be.

**Comment by mattstauffer** [comment]
Thanks @benswinburne!
