### ISSUE TITLE
"Valet open" would be safer at the end in case someone has customized their domain

### ISSUE THREAD

**Issue by mattstauffer** [tightenco/lambo#2]
... but that seems to require a sudo password every time?

**Comment by RobinMalfait** [comment]
I don't need sudo for valet open,  strange

**Comment by michaeldyrynda** [comment]
You shouldn't do; `valet open` should just read from the configuration file and open `<directory>.<domain>`, rather than assuming `.dev`

**Comment by mattstauffer** [comment]
![image](https://cloud.githubusercontent.com/assets/151829/17353029/c18ffb68-5909-11e6-9438-6d971467a905.png)

Wondering if this is a bug since I had early versions of Valet on my system? @adamwathan @taylorotwell is this a sign that I need to dump and re-install Valet? Thanks!

**Comment by michaeldyrynda** [comment]
Sounds like you don't have a sudoers entry, which is why it's asking. That was added in `v1.1.4` as far as I can tell - if you run `valet install` again, that should fix it for you :)

**Comment by RobinMalfait** [comment]
@michaeldyrynda `valet open` doesn't assume that you are using `.dev` ;)

**Comment by mattstauffer** [comment]
@RobinMalfait A) I made the issue. B) you misread Michael's comment. :)

**Comment by RobinMalfait** [comment]
@mattstauffer I'm dumb.

a) Ok confused, I thought I made the issue because I almost never respond to issues.
And I got emails from this issue so I thought I made it, silly me.

b) I'm I'm, I'm sorry; I indeed read it wrong..

**Note to self**: do not respond to issues when it's late in the evening :)

**Comment by mattstauffer** [comment]
@RobinMalfait <3 <3 <3

**Comment by mattstauffer** [comment]
https://github.com/tightenco/lambo/commit/e5c8ff3080e437cd6acfddfee92bf7bd55a25cfd
