### ISSUE TITLE
Add a `.lambo` file

### ISSUE THREAD

**Issue by mattstauffer** [tightenco/lambo#25]
I'd really like to not have to pass the same config flags every time I use Lambo. I'd love to be able to define my editor and other preferences once.

**Comment by milose** [comment]
So have a `~/.lambo/config` file to include settings?

Maybe it would be nice to have a `~/.lambo/includes` folder with files to copy / overwrite on every new project. For example `.editorconfig`, `.eslint`, `.travis.yml`; or sometimes, you want to overwrite the original `.gitignore` file.

Seems reasonably useful.

**Comment by mattstauffer** [comment]
That's an interesting idea. Definitely something to consider!

**Comment by quickliketurtle** [comment]
A Simple solution would be to create a ~/.lambo file and source that after the initial variable definition on line 54. ```source ~/.lambo```

The .lambo file would just have variables you wanted to set so if I just wanted to set my editor the file would be:
```
EDITOR='subl'
```

Could add validation to make sure variables are set or valid etc. 

For the includes idea, that could be cool.  I'm thinking on a higher level we could add an 'after' function that looks for a .lambo-after file and processes any commands in there after the lambo script.  That could allow the includes idea to be executed but not build the structure into lambo. Just a thought to keep the lambo script simpler. This could work for a 'before' option as well but I don't have a use case in mind for that.

**Comment by mattstauffer** [comment]
Additional note: I'd love to add "packages to include every time i spin up a new app", which would run `composer require` for each package .

**Comment by mattstauffer** [comment]
This is done but there are a few ideas in this thread we should extract to separate issues.
