### ISSUE TITLE
Handling applications that already exist

### ISSUE THREAD

**Issue by philip** [tightenco/lambo#28]
Feature request to handle the following exception:
```
 [RuntimeException]
  Application already exists!
```
How? I'm not sure. Maybe add `--force` to continue doing the stuff that's not `laravel new *`, otherwise exit with a friendly message. Not sure if it should also completely replace the directory.

**Comment by milose** [comment]
I don't think we should overwrite anything with `lambo`. It is just a tool for quick project creation. I submitted a PR #30 to check if the given directory exists, and also to handle other exceptions and missing commands.
