### ISSUE TITLE
Would be nice to allow for opening in editor afterward as well

### ISSUE THREAD

**Issue by mattstauffer** [tightenco/lambo#3]
Something global config to define what the editor command is (or just a series of hooks?)
So that after the thing runs, it would then run "mvim ." or "subl ." or whatever

**Comment by RobinMalfait** [comment]
You can set an $EDITOR variable and use that. I think that there is already a $EDITOR not sure though, on my phone atm haha

**Comment by mattstauffer** [comment]
I have been thinking about something like a global config file (`~/.lambo`) with convenience methods to set it:

```bash
lambo config:set editorCall "mvim ."
```

Need to think about that a bit.

**Comment by lstables** [comment]
Having asked @mattstauffer on Twitter, I want to edit the lambo script on my machine to cd into the newly created project using iTerm and then also open in Sublime.
How would I achieve this?
