### ISSUE TITLE
Proposal: After script

### ISSUE THREAD

**Issue by quickliketurtle** [tightenco/lambo#36]
Proposal: 
Add check for after script to allow additional commands after main Lambo script is complete.

Background:
There were 2 suggestions from issue #25 

1. Maybe it would be nice to have a ~/.lambo/includes folder with files to copy / overwrite on every new project. For example .editorconfig, .eslint, .travis.yml; or sometimes, you want to overwrite the original .gitignore file. @milose 
2. I'd love to add "packages to include every time i spin up a new app", which would run composer require for each package . @mattstauffer 

Details:
I propose simply adding a check for a `~/.lambo/after` file and including it. 
```bash
if [[ -f ~/.lambo/after ]]; then
    echo "Running additional commands"
    source ~/.lambo/after
fi
```

The `after` file would be a plain bash script so you could do 'anything' here.

Example `after` file for use case 1:
```bash
#!/usr/bin/env bash

echo "Copying Files"
cp -R ~/.lambo/includes/ $PROJECTPATH
```

Example `after` file for use case 2:
```bash
#!/usr/bin/env bash

echo "Installing composer dependencies"
composer require tightenco/mailthief tightenco/quicksand
```

Any feedback on this approach? 

We could add a make and edit command (like config has) and include a sample command commented out to give people some ideas... better than a blank slate i think. 

Thanks.

**Comment by mattstauffer** [comment]
I *love* it.

**Comment by quickliketurtle** [comment]
👍 Just submitted PR #37 🎉
