### ISSUE TITLE
Editor opens before yarn runs

### ISSUE THREAD

**Issue by lukeberry99** [tightenco/lambo#41]
When creating a new site the editor is opened before `yarn` is ran, this doesn't cause an issue when using editors such as PHPStorm or Sublime, but when using vim this halts the rest of the setup process until vim has been closed. This means that yarn doesn't run, auth scaffolding doesn't run and any `lambo-after` config doesn't run either.

**Comment by milose** [comment]
You are right, `vim` is a foreground running process.

We could move the editor opening command to the end of the script, but it would affect users using other editors.

We could also detect if `vim` is set as an editor and push the command to the end of the queue.

I would like to discuss these options.

Alternatively, if on Mac, you could `touch ~/.lambo/lambo-vim.sh`
Then, add these lines:
```bash
#!/usr/bin/env bash
osascript -e '
 on run argv
 tell application "Terminal"
     activate
     tell window 1
        do script "cd " & item 1 of argv & "&& vim " & item 2 of argv
     end tell
 end tell
 end run
' "$PWD" "$1"
```
Make it executable `chmod +x ~./lambo/lambo-vim.sh` and in `~/.lambo/config` modify the line `CODEEDITOR="vim"` to `CODEEDITOR="~/.lambo/lambo-vim.sh"`.

This will open a new terminal **window** with `vim`, and continue batch running `yarn` and other scripts.

**Comment by lukeberry99** [comment]
Personally I'm not too keen on opening `vim` in a new window - I use tmux and would much prefer `vim` to open in the current pane, or in a split.

Detecting if `vim` is set as the editor is certainly an option - however we'd need to check for `vi`, `vim`, `nvim`, `emacs`, `nano`, `pico`, etc, etc. There are a lot of foreground editors and I'm not sure if making changes on a case-by-case basis is the appropriate action.

We could add a new config option to defer opening the editor until after the other operations have completed, this would be disabled by default - it then wouldn't affect users using other editors and anyone could opt-in to it, meaning we wouldn't have to add a check for each type of foreground terminal editor.

What are your thoughts?

**Comment by milose** [comment]
Yup, configuration option should probably be the best way to go about this. But I would wait for more opinions before submitting the PR.

**Comment by lukeberry99** [comment]
I've added this locally for the time being, and it works well for me. I'll hold off before I submit it as a PR though.

**Comment by mattstauffer** [comment]
Config option is definitely possible. But I'm also not super mad at basically keeping an array of the editors which we expect to open in the terminal; that's a finite list and i feel like the more config options we have the worst it's going to be. 

Thoughts anyone?

**Comment by milose** [comment]
I'd rather add `EDITOR_RUNS_LAST=true` to the config then mess with editor names in lambo source code. That would mean a new version every time an editor pops up.

More config options are not bad if we aren't cluttering the command argument list, I think.

Or we could just move the editor process back to the end of the batch and be done with it.

**Comment by lukeberry99** [comment]
I'm open to both ideas, not too keen on moving the editor process to the end of the batch globally though, as for other editors there's really no need to wait for the yarn/gulp process to run.

I think I prefer the idea of the config option, we can remove it from the command list and just have it in the file?

**Comment by mattstauffer** [comment]
I appreciate all the conversations we've had here but I would like to prioritize user onboarding/simplicity even if it means slightly dirtier code. I would like this to happen as an inline switch that sniffs against the command line editors and then we call it a day.

Thanks!

**Comment by lukeberry99** [comment]
On it @mattstauffer, I'll submit the PR in the next few days.


Cheers
