### ISSUE TITLE
post-install-cmd is not defined

### ISSUE THREAD

**Issue by quickliketurtle** [tightenco/lambo#45]
[InvalidArgumentException]                                
  Script "post-install-cmd" is not defined in this package

In laravel 5.5 the post-install-cmd has been removed. The laravel installer was updated to account for this https://github.com/laravel/installer/commit/3044997716d6e4fddac315f5d26689382bb378bc#diff-2f97ce541989fd5777bb883c213d1805

Move info here: https://laravel-news.com/laravel-5-6-removes-artisan-optimize

We need to updated the version requirement of the laravel installer dependency to v1.4.1 to account for this.

**Comment by mattstauffer** [comment]
Is this less because it's a dependency, and more just because everyone should update so this will encourage them to update?

**Comment by quickliketurtle** [comment]
I guess the only negative to not updating is you get an error. Everything still works as expected.  I just die a little on the inside when I see a big red error on the screen. ¯\_(ツ)_/¯

**Comment by mattstauffer** [comment]
Hah yah not our responsibility. :) <3
