### ISSUE TITLE
Allow Initial commit to be empty

### ISSUE THREAD

**Issue by djallits** [tightenco/lambo#51]
I am a big believer of the initial commit being empty: `git commit --allow-empty -m 'Initial Commit'`. This should occur immediately after the `git init`. This would then be followed with the `git add .` and the `git commit -m $MESSAGE` as found in [line 307](https://github.com/tightenco/lambo/blob/7b849a5658e11ef8f6268234d06bb2b2d0731d22/lambo#L307).

I can quickly create a PR if this would be considered.

**Comment by mattstauffer** [comment]
@djallits Huh, I've never heard of this before. Could you explain a little bit of why you would prefer this?

Thanks!

**Comment by djallits** [comment]
Hey @mattstauffer Thanks for the quick reply.

It is still my understanding that you cannot rebase the initial root commit, therefore starting with an empty commit at the root would push all source additions to subsequent commits, alleviating the developer of this problem. This is typically only relevant in the early days of a project.

Another use case would be providing a developer a reference commit if they were to create a releases/v2 branch (think GitFlow here).

This is probably an edge case for sure, and definitely a personal preference on my and a few others end. However, there doesn't seem to be a mechanism to alter this flow. The alternative, and it would be acceptable, is to roll back the commit in the `after` script.

**Comment by mattstauffer** [comment]
@djallits huh, that makes sense--gonna push this out to twitter to see if there are any downsides. Thanks!

**Comment by rtablada** [comment]
I'm more of the opinion that initial commit should be the framework initialization (including any lockfile). Ember goes by this pattern and running `ember new project-name` creates the project, installs dependencies, then commits the fully bootstrapped project.

**Comment by FatBoyXPC** [comment]
I previously would have said something to the effect of "In what scenario would you want to rebase your first commit?" However, just last week, I started a new Laravel project and didn't realize until significantly later that `public/js/app.js` and `public/css/app.css` weren't ignored. I wanted to rebase this change, and was stuck doing it on the 2nd commit instead of first!

**Comment by nickknissen** [comment]
@rtablada By doing what OP purposes, the initial project files will still be commited. So it would not be necessary to re-run the bootraping script.
```sh
git init
git commit --allow-empty -m 'Initial Commit'
git add .
git commit -m $MESSAGE
```

**Comment by martinbean** [comment]
> It is still my understanding that you cannot rebase the initial root commit

@djallits Wrong: `git rebase -i —root`

**Comment by djallits** [comment]
@martinbean Thanks, I didn't know about the root flag.

**Comment by mattstauffer** [comment]
I think this is enough of an edge case that I'm going to say that people who want to do this can get familiar with interactive rebase (and, obviously, this issue is super old.) Thanks for constructive conversation everyone!
