### ISSUE TITLE
Branch lampho - PHP Laravel-Zero version roadmap

### ISSUE THREAD

**Issue by ijpatricio** [tightenco/lambo#55]
Hello Matt,

So after checking https://github.com/tightenco/lambo/tree/lampho

I'm wondering why it stopped, or still didn't replace the shell version?

I can see some points

- Was multiOS was an issue?

- Composer global requiring was an issue because of dependencies flattening, and possible collision?
-Would you see https://github.com/consolidation/cgr as fit?

![image](https://user-images.githubusercontent.com/26031459/43098007-bafb1830-8eb5-11e8-96d2-811a3e5ad792.png)

But please let me know your point of view, Lambo in php/Laravel-Zero would be even more awesome, by adding few things:

- Tests
- Creating database optionally for the 'new' command
- Own sqlite database to store options, and easily work with them (internal, for lambo use, in ~/.lambo)
- Laravel console menu to interact
- Having user Classes/Events in ~/.lambo/Events
- Firing events after project installed, from lambo interactive menu... 
  - A sub set of events could be adding predefined packages array
  - Also custom recipes... php recipes on the classes, or shell commands invoked from lambo
- Lambo clone, for fully working projects, we could try them out, from A-Z, with this one command
  - database created, migrated, seeded, etc
  - even having a composer.json key in the repos, to process after lambo :)

I see possibilities as endless, and would contribute for sure..

Let me know what you think, please, if you have some roadmap.. Or even if you share these ideas at all, or have some others?

**Comment by mattstauffer** [comment]
@ijpatricio Thanks for your notes! The only reason it stopped is because the guy working on it stopped. I assume he didn't have time anymore. I would love for anyone interested to pick it up.

I wasn't so concerned about the dependencies; anyone who cares about that can use cgr as you described.

My number one goal is to get the app working exactly the same way it does right now and then we can replace the shell-script with the PHP version. *Then* we can talk about new features. Make sense/sound wise? If you're interested in working on this that'd be awesome--just let me know what you need from me!

**Comment by ijpatricio** [comment]
My pleasure @mattstauffer !

Sure, I would love to! 

Totally makes sense, starting from where it is right now.
So feature list, I'll get it from the lateste release v0.4.2, right?

Well, it would be awesome to know:
- In which branch repo to start with?
- Can it be based on Latest stable Laravel-Zero?
- I'm not sure I will be able to develop the test cases alone with the best approach, let's see when we get there?

**Comment by mattstauffer** [comment]
- In which branch: you can fork from lampho branch, I guess?
- Yep, latest Laravel Zero is great
- Sure, let me know--and I know Nuno is happy to help often as well.

**Comment by ijpatricio** [comment]
Hey @mattstauffer,

- In which branch: Sure, I can fork from it. (Will replace almost all of it though)
- Already started it!
- Thanks! And yeah, for sure, I can ping Nuno also, great idea! :)

As I'm already on it, and changing from bash to Laravel console...
Would you see fit asking options interactively instead of inline?

Example:
```
$this->choice('Release or Dev branch?', ['Release', 'Dev'], $default = 0, $attempts = 3);
```
(Even checking which exists before asking, like editors)

**Comment by ijpatricio** [comment]
Ok @mattstauffer, so I was happy to see the braindump.md file :)

I started a little, in the fork https://github.com/ijpatricio/lambo/tree/ijpatricio-lampho-1
I still didn't do PR, not to make any mess.

Any chance you can clone from there, and check what you like and dislike?
It's still missing many features, but has some already, and you can check if you like the approach.

- Question classes
- Verification Classes
- config and after files generation, and merging with config

Don't want to get long here, I would say maybe in 10 minutes, you can quickly navigate in the app, and check it out??

Oooh and generate the after file, to see (hear) it in action ahah

I will continue it for sure, but would be amazing to get some feedback along the way!

Thanks!

**Comment by ijpatricio** [comment]
Hey again,

So this is how it's looking. Hope you dig it!! :)

![image](https://user-images.githubusercontent.com/26031459/43355925-4f439d04-925e-11e8-9b3f-d6cf707ea2f5.png)

**Comment by ijpatricio** [comment]
@mattstauffer Sorry if this is considered spamming :P

As i'm not sure if you will have time clone and inspect the app...

Now it's possible to override base config + ~/l.lambo/config.php with the options.

This is similar to the original one, but I guess better, right?

![image](https://user-images.githubusercontent.com/26031459/43356854-580f784c-9270-11e8-909a-25a958310e6d.png)

**Comment by jonsugar** [comment]
@ijpatricio / @mattstauffer 

I'm closing this because:
- the last activity on this branch was on 28 Jul 2018.
- there is a current ongoing effort to port Lambo to PHP which is released as an alpha with a beta coming soon.
