### ISSUE TITLE
Reference to Laravel Valet config.json domain is incorrect, is now tld

### ISSUE THREAD

**Issue by ovvessem** [tightenco/lambo#61]
https://github.com/tightenco/lambo/blob/ffce7569e7b8d4916f71698d6ffc5ec24b3a9f3f/lambo#L178

**Comment by lmatab** [comment]
TLD=$(php -r "echo json_decode(file_get_contents('$HOME/.config/valet/config.json'))->domain;") 
 is just trying to get the TDL that is assigned in Valet, I did hard coded to .test and it worked like a charm, it is a problem with Valet no Lambo

**Comment by mattstauffer** [comment]
@lmatab Please upgrade Lambo and try again--it should now handle the fact that Valet offers both ->domain and ->tld.

https://github.com/tightenco/lambo/releases/tag/v0.4.4. Thanks!

**Comment by lmatab** [comment]
@mattstauffer  thanks a lot!,it  works nicely now!, I missed a lot to be able to use Lambo!, thanks again for sharing this great software with the community.

**Comment by mattstauffer** [comment]
@lmatab So glad to hear it! Sorry it took so long! :) <3
