### ISSUE TITLE
Re-work `--auth` to use new `--auth` flag on the installer

### ISSUE THREAD

**Issue by mattstauffer** [tightenco/lambo#80]
https://twitter.com/taylorotwell/status/1196556840575938560
AND THERE WAS MUCH REJOICING

**Comment by jonsugar** [comment]
Released in [v1.0.0-alpha2](https://github.com/tightenco/lambo/releases/tag/v1.0.0-alpha2) as part of the migration to PHP. See, [RunLaravelInstaller.php](https://github.com/tightenco/lambo/blob/v1.0.0-alpha2/app/Actions/RunLaravelInstaller.php)
