### ISSUE TITLE
lambo edit-config throws error

### ISSUE THREAD

**Issue by spaantje** [tightenco/lambo#90]
When running `lambo edit-config` or `lambo edit-after` i get the following error: 

```
In Filesystem.php line 52:

File does not exist at path phar:///Users/s.spaan/.composer/vendor/tightenco/lambo/builds/lambo/stubs/config.stub
```

```
In Filesystem.php line 52:

File does not exist at path phar:///Users/s.spaan/.composer/vendor/tightenco/lambo/builds/lambo/stubs/after.stub
```

Running version v1.0.0-alpha3

**Comment by jonsugar** [comment]
Confirmed. 

@mattstauffer I will look into this.

**Comment by jonsugar** [comment]
Hmm. Not fixed. Totally busted now. I'm investigating.

**Comment by spaantje** [comment]
@jonsugar @mattstauffer let me know if i can do anything to help!

**Comment by mattstauffer** [comment]
Should be fixed now--let me know!

**Comment by spaantje** [comment]
Yes it's working ! Thanks!
