### ISSUE TITLE
Failed installing alpha version

### ISSUE THREAD

**Issue by devmsh** [tightenco/lambo#92]
<img width="803" alt="Screen Shot 2020-03-21 at 21 21 16" src="https://user-images.githubusercontent.com/9499808/77233657-f7477a80-6bb9-11ea-87db-9311cbbc7308.png">

**Comment by mattstauffer** [comment]
@devmsh I'm guessing that you have something that conflicts with the Laravel installer.
Can you try requiring the installer first?

```
composer global require laravel/installer v3.0.1
```

I expect this to show errors, but those errors will be helpful for us.

**Comment by devmsh** [comment]
<img width="590" alt="Screen Shot 2020-03-22 at 17 30 55" src="https://user-images.githubusercontent.com/9499808/77252047-ed2d8680-6c62-11ea-8120-78f3711a58dc.png">

It's installed successfully, and I tried to reinstall lambo again and it just works fine.

**Comment by jonsugar** [comment]
@devmsh can you close this then?
