### ISSUE TITLE
Decide: Add --with-telescope option and --with-nova option? or are these recipes?

### ISSUE THREAD

**Issue by mattstauffer** [tightenco/lambo#95]

**Comment by regiszanandrea** [comment]
Hi,

This references to https://github.com/laravel/installer/pull/109 ?

**Comment by mattstauffer** [comment]
@regiszanandrea Not exactly sure your question, but I do remember having a conversation with you about this. You'll be happy to know that I'm building out the "presets" option right now; the current planned syntax will be like this:

```bash
lambo myProject --presets="telescope|nova"
```

You can see the process on my live stream archives on YouTube:

https://www.youtube.com/playlist?list=PLgJIx0-UaB9QEVnD9yE60vBw5CNZmpYBh

**Comment by regiszanandrea** [comment]
Nice, Do you pretend to launch lambo with presets of other packages too, like Socialite, or you will leave open to community improve that ?

**Comment by mattstauffer** [comment]
@regiszanandrea It'll launch with Nova, Telescope, Blueprint, and maybe one or two others, but yah, I think I'd rather launch early and let many folks contribute than do them all myself. :)
