### ISSUE TITLE
Composer output appearing as "errors" even though they aren't errors

### ISSUE THREAD

**Issue by m50** [tightenco/lambo#99]
Pinging @jonsugar @mattstauffer 

I mentioned on the stream that at the end of any composer call, to add `2>&1` to output, and it will still spit everything out from composer, but to stdout instead of stderr.

@mattstauffer had mentioned using `--quiet` on composer calls, which would work, but you couldn't see the install output if you wanted.

Maybe it would be a good idea to always do `2>&1` and then have an option to have lambo pass `--quiet` to composer calls?

(As I closed the twitch window, I noticed @jonsugar had said something, but I missed what, so I figured I'd share here so there can be a discussion on the best option)

**Comment by jonsugar** [comment]
Closing this as it is superseded by #102.
